services:
  - docker
# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
script:
  - docker-compose -f docker-compose-build.yaml build --parallel
# Do similar for other three images
# Tagging
  - docker tag udagram-api-feed pandareveluv/udagram-api-feed:v1
  - docker tag udagram-api-user pandareveluv/udagram-api-user:v1
  - docker tag udagram-frontend pandareveluv/udagram-frontend:v1
  - docker tag udagram-reverseproxy pandareveluv/udagram-reverseproxy:v1
# Do similar for other three images
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pandareveluv/udagram-api-feed:v1
  - docker push pandareveluv/udagram-api-user:v1
  - docker push pandareveluv/udagram-frontend:v1
  - docker push pandareveluv/udagram-reverseproxy:v1
# Do similar for other three images